apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager-issuer
  namespace: ingress-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 1m
  path: ./source/07_ingress/3
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client
