apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: nginx-ingress
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb
  interval: 1m
  path: ./source/07_ingress/5
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: nginx-ingress
      namespace: ingress-system
